version: 1

rules:
  # Protect centy configuration
  - path: '.centy/**'
    access: read
    reason: 'use centy cli to edit this folder'

  # Block key files
  - path: "^.*\\.key$"
    type: regex
    access: none
    reason: 'Key files contain sensitive credentials'
