'use client'

import {
  createIssue,
  updateIssue,
  deleteIssue,
  createDoc,
  updateDoc,
  deleteDoc,
  updateConfig,
  createUser,
  updateUser,
  deleteUser,
} from './write'
import {
  shutdown,
  restart,
  init,
  registerProject,
  untrackProject,
  setProjectFavorite,
  setProjectArchived,
  setProjectOrganization,
  setProjectUserTitle,
  setProjectTitle,
} from './daemon'
import {
  createOrganization,
  updateOrganization,
  deleteOrganization,
  syncUsers,
  createLink,
  deleteLink,
  updateLink,
  addAsset,
  deleteAsset,
  getAsset,
} from './org-write'
import { openInTempVscode, openInTempTerminal } from './workspace'
import { moveIssue, duplicateIssue, moveDoc, duplicateDoc } from './entity-ops'

export const writeHandlers = {
  createIssue,
  updateIssue,
  deleteIssue,
  createDoc,
  updateDoc,
  deleteDoc,
  updateConfig,
  createUser,
  updateUser,
  deleteUser,
  shutdown,
  restart,
  init,
  registerProject,
  untrackProject,
  setProjectFavorite,
  setProjectArchived,
  setProjectOrganization,
  setProjectUserTitle,
  setProjectTitle,
  createOrganization,
  updateOrganization,
  deleteOrganization,
  syncUsers,
  createLink,
  deleteLink,
  updateLink,
  addAsset,
  deleteAsset,
  getAsset,
  openInTempVscode,
  openInTempTerminal,
  moveIssue,
  duplicateIssue,
  moveDoc,
  duplicateDoc,
}
